### ISSUE TITLE
Not working CentOS 7

### ISSUE THREAD

**Issue by pryg-skok** [Rodeo314/libmfx#2]
Hello, I'm trying to use your package to provide libmfx in my system in automatic way. But your package doesn't working:
```
[root@localhost libmfx]# ls
AUTHORS    compile       config.sub    COPYING  include  install-sh  libmfx.vcproj  Makefile.am  NEWS    readme-dispatcher.rtf
ChangeLog  config.guess  configure.ac  depcomp  INSTALL  libmfx.sln  ltmain.sh      missing      README  src
[root@localhost libmfx]# autoconf 
configure.ac:4: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:10: error: possibly undefined macro: AM_PROG_LIBTOOL
[root@localhost libmfx]# ./configure
./configure: line 1773: syntax error near unexpected token `1.10'
./configure: line 1773: `AM_INIT_AUTOMAKE(1.10 no-define subdir-objects)'

[root@localhost libmfx]# autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.


[root@localhost libmfx]# gcc --version
gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9)
```

How can I fix it?
Thank you!

**Comment by Rodeo314** [comment]
Let me get back to you tomorrow or the day after, if you don't mind.

Regards,

Tim

**Comment by pryg-skok** [comment]
It's OK! Thank you.
I've found another project: https://github.com/lu-zero/mfx_dispatch
It works ok. So if you don't interested in improvements in your project - you may just close this issue, I think.

**Comment by Rodeo314** [comment]
I was going to recommend it. The only advantage to my package is that it
matches the latest SDK from Intel, whereas Luca's hasn't been updated since
late 2013. This is mostly useful if you provide a libmfx-devel package with
Media SDK headers. But you could also merge both manually.

Tim

**Comment by pryg-skok** [comment]
Hm, maybe we need to make new repo with working build system and also actual? :-)

**Comment by Rodeo314** [comment]
I'll update mine sometime next week, maybe I can take a look at the build system.

That or I'll contact Luca about merging both repos later this year.

Tim

**Comment by Rodeo314** [comment]
I finally actually looked at Luca's mfx_dispatch and it's more current than I thought. The outdated one is at http://git.videolan.org/?p=mfx_dispatch.git;a=summary - but https://github.com/lu-zero/mfx_dispatch should be OK to use for just about anything except the very latest Media SDK features.
